# user variables, change this to make custom site.

name: 「ELITE NEWS」
desc: Informação de bolso para otakus imundos!
author: HirohikoAraki
  name: Hirohiko Araki
  avatar: //gravatar.com/avatar/daa1cc36ed2ab0d13045d5cd2431cde9?s=320
  profile: |
    “The editors-in-chief generally only work during the afternoon. For the past twenty years, I've brought my script to the Shueisha building in the middle of the morning and I show it to the only person who is working at that hour. This person is the very first editor-in-chief of "JoJo's Bizarre Adventure" and their impressions and suggestions are very important to me. If I went there during the afternoon and met another editors, I would have produced a very different work.
    Destiny isn't founded on chance, it has its reasons. In "JoJo's", it's on that point of view that one bases themselves. It doesn't have much sense scientifically, but this is how I feel.”

    — Hirohiko Araki
  socials:
    facebook:
    twitter: //twitter.com/#
    google-plus:
    github: //github.com/#
    stack-overflow: //stackoverflow.com/users/#
    instagram:
    pinterest:
    steam: //steamcommunity.com/id/#
license: MIT License


# theme variables, change this to make site looks best.
baseurl: /blog
paginate: 2


# system variables, do not change unless you knew what's it does.
paginate_path: page/:num
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

sass:
  sass_dir: _sass
  style: compressed
